"""changed create to created again

Revision ID: 5c14e8307d74
Revises: c316ec92e560
Create Date: 2023-09-01 13:29:18.391865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c14e8307d74'
down_revision = 'c316ec92e560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATE(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
