"""changed create to created

Revision ID: c316ec92e560
Revises: e685317c5a85
Create Date: 2023-09-01 13:26:20.892541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c316ec92e560'
down_revision = 'e685317c5a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATE(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
